baseURL = "https://anggiaj.github.io/"
languageCode = "en-us"
title = "random peasant shouts"
theme = "hugo-theme-console"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pastie"
    tabWidth = 4
